### PR TITLE
Enable direct execution with python -m vpn_slice

### PR DESCRIPTION
**Pull request by dnut**
This is meant to be run as an app but the user needs to create a python script just to use it. There should be a \_\_main__.py file to allow users to run the script with `python -m vpn_slice`

### CODE REVIEW

**Comment by dlenski** [comment]
> This is meant to be run as an app but the user needs to create a python script just to use it.

The package's `setup.py` already installs `vpn-slice` as a CLI entry-point (https://github.com/dlenski/vpn-slice/blob/master/setup.py#L34). Does that not work for you?

> There should be a __main__.py file to allow users to run the script with `python -m vpn_slice`

Yeah, we should just rename `main.py` to `__main__.py` to make this easier to run without installation. :ok_hand:

**Comment by dlenski** [comment]
> Yeah, we should just rename `main.py` to `__main__.py` to make this easier to run without installation. :ok_hand:

Done in 7c81425

**Comment by dnut** [comment]
> The package's setup.py already installs vpn-slice as a CLI entry-point (https://github.com/dlenski/vpn-slice/blob/master/setup.py#L34). Does that not work for you?

I tried the `vpn-slice` command and it did not work. I didn't know about entry_points. Does it add bash functions? How is it supposed to do that?

> Yeah, we should just rename main.py to __main__.py to make this easier to run before/without installation, such as for debugging purposes while developing.

I recommended adding a second file because it breaks backwards compatibility for anyone who is importing from main. Also I think there may be issues if you try to import anything from \_\_main__.py, but I'm not sure about the details. I usually put my entire app in other files and just use \_\_main__.py to call one imported function.

**Comment by dlenski** [comment]
> I tried the `vpn-slice` command and it did not work. I didn't know about entry_points. Does it add bash functions? How is it supposed to do that?

It's platform-dependent, but at least my `pip3`/`setuptools` (on Linux) installs shortcuts in `~/.local/bin`. See https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation.

> I recommended adding a second file because it breaks backwards compatibility for anyone who is importing from main.

If I were renaming any other module, I'd agree, but since `__main__.py` (formerly `main.py`) is used *only* for the command-line entry point and helper functions, no one should be importing anything from them, anyway. This file is *just* there to provide the CLI.

> Also I think there may be issues if you try to import anything from \_\_main__.py, but I'm not sure about the details. I usually put my entire app in other files and just use \_\_main__.py to call one imported function.

As long as you use the `if __name__=='__main__': main()` formula, there are no issues with importing from `__main__` (though again, I'd consider it bad practice to put anything API-ish in there).

**Pull request closed without merging**
