### PR TITLE
fix attempt_reconnect issue

### PR DESCRIPTION
**Pull request by doomedraven**

### CODE REVIEW

**Comment by dlenski** [comment]
The point of this is to handle the `reason=attempt-reconnect` case added in [openconnect MR !17 on Gitlab](https://gitlab.com/openconnect/openconnect/issues/17), right?

It appears from [this comment](https://gitlab.com/openconnect/openconnect/issues/17#note_131764677) that the `attempt-reconnect` case should, at minimum, set or reset an explicit route to the VPN gateway through the non-VPN interface… yes? (Similar to: https://github.com/dlenski/vpn-slice/blob/69476c58fb5e3538f30ec38a24bf987c4bd4918e/vpn_slice/main.py#L93-L95)

@dwmw2, do I have that right? I'm a little bit confused about how/why a drop-and-reconnect would leave the routing table in a state where the external address of the VPN gateway is routed through the VPN… ¯\\\_\(ツ\)\_/¯

**Comment by doomedraven** [comment]
yes for that, hm i didn't have any problem with routing after that, but i will double check tomorrow

**Comment by doomedraven** [comment]
ok tested, in my case vpn autoreconnected 4 times today, without any extra change apart of that add to Enum

**Comment by dlenski** [comment]
I'm gonna merge this because it doesn't do any harm and suppresses the error message.

I added a warning and comment, and still would love to get @dwmw2's take on what `attempt_reconnect` *should* do, in general.

**Comment by dwmw2** [comment]
Connect to a full-tunnel VPN, and vpnc-script adds a default route to the tun device *and* a specific route to the VPN server over the physical device. Without the latter, we just send packets for the VPN... back to OpenConnect over the tun device. 

Disconnect the underlying physical device, and the routes on it go away. Including the specific route to the VPN server. Now bring the underlying device back up, and only the normal routes get added. You get a default route through it, but with lower priority than the VPN default route that still exists.

The attempt-reconnect invocation is supposed to restore the specific route to the VPN server, without which reconnecting won't actually work.

**Comment by dlenski** [comment]
> Disconnect the underlying physical device, and the routes on it go away. Including the specific route to the VPN server. Now bring the underlying device back up, and only the normal routes get added. You get a default route through it, but with lower priority than the VPN default route that still exists.

Ah, that makes sense now. I wasn't clear on _how_ this could happen.

> The attempt-reconnect invocation is supposed to restore the specific route to the VPN server, without which reconnecting won't actually work.

Right. That's what [I thought it needed to do](https://github.com/dlenski/vpn-slice/pull/14#issuecomment-488129621).

However, in order to know what network device it should use to (re)create the route-to-gateway, the `vpnc-script` would need to know the identity of the newly-restored underlying physical device. How should it figure that out?

**Comment by dwmw2** [comment]
This, I fear, is a very good question.

**Comment by dlenski** [comment]
> This, I fear, is a very good question.

Basically, when doing the _initial_ connection, the `vpnc-script` should just ask, "what is the current route to the gateway?", followed by "okay, set that as an explicit /32 or /128 route"

Upon reconnection-of-the-underlying-device, what I _think_ it should do is ask, "what is the current route to the gateway?", but then if that route to the gateway goes through its own tunnel interface (`TUNDEV`) it should follow-up with, "hmmm, okay, but what would be the route to the gateway excluding all the routes through my `TUNDEV`?", and then set _that_ as the explicit route to the gateway.

The trouble is that I don't know how to use [`ip route get`](https://linux.die.net/man/8/ip) to ask for a route while _excluding_ a specific network device. Any ideas?

**Comment by dlenski** [comment]
_If_ you already know the name of the underlying interface, you can get the correct route to the gateway _via that interface_ with `ip route get $VPNGATEWAY oif $INTERFACE`… but of course what I really want is `ip route get $VPNGATEWAY oif anything-except-$TUNDEV`.

One blunt approach would be to (1) _delete_ any default route on `$TUNDEV`, (2) reset the route to the gateway, (3) recreate the default route on `$TUNDEV`. This seems bad because because after (1) and before (3), assuming it succeeds, packets intended for the VPN will not only _not_ get queued for `$TUNDEV`, they _will_ get sent to another inappropriate interface.

Yeah, that's a potential fail-open security hole… urk.

**Comment by dlenski** [comment]
See https://gitlab.com/openconnect/vpnc-scripts/-/merge_requests/14 for where I've attempted to add actual support for `attempt-reconnect` in the "standard" `vpnc-script`.

**Pull request merged**
