### PR TITLE
Add macOS support

### PR DESCRIPTION
**Pull request by gmacon**
This adds support for macOS as discussed in #5.

### CODE REVIEW

**Comment by dlenski** [comment]
It seems fine to me, although I have no way to test the MacOS functionality. (A test suite will be useful here sooner or later…)

But please fix the unnecessary code formatting changes, as discussed in #5.

**Comment by gmacon** [comment]
Sure. I thought I'd fixed them all, and I'm apparently too close to this code to see whatever is left. Can you point me to them (really just one of each type; knowing exactly what to look for will make them easier to find)?

**Comment by kalvinwang** [comment]
@dlenski I looked at the latest diff here and don't see any code formatting changes remaining of the type you mentioned (apostrophes and multiline arguments), would you mind merging this branch? It's really helpful for Mac users. Thanks! (and thanks to @gmacon as well!)

**Comment by XL64** [comment]
I would like to have a look and maybe resolve the conflicts from another fork but I don't know how to build it correctly.
I did python3 setup.py build but it only builds a build/lib/vpn_slice with no vpn_slice python file. And when I try to run the main.py it says : "main.py: error: Must be called as vpnc-script, with $reason set".
What did I miss ?

**Comment by gmacon** [comment]
I've rebased my branch on top of the current master.

@XL64: I don't think your error is related to this PR. I think your issue is that vpn-slice does not expect the --script-tun option (which routes all traffic through the command provided by --script). Try it without that option.

**Comment by XL64** [comment]
@gmacon Indeed I had to remove this option, thanks for rebasing :)

**Comment by modib** [comment]
Tested this on macOS Mojave 10.14.3 and it seems to be working fine so far with some basic testing. Will be testing more throughout the week.

cmd used:
`sudo openconnect <host> -b -l -q -u <user> --authgroup=<authgroup> -s '/usr/local/bin/vpn-slice x.x.x.x/22'`

**Comment by modib** [comment]
`Exception while setting reason from environment variable reason='attempt-reconnect'
Traceback (most recent call last):
  File "/usr/local/bin/vpn-slice", line 11, in <module>
    load_entry_point('vpn-slice==0.1', 'console_scripts', 'vpn-slice')()
  File "/usr/local/lib/python3.7/site-packages/vpn_slice-0.1-py3.7.egg/vpn_slice/main.py", line 331, in main
  File "/usr/local/lib/python3.7/site-packages/vpn_slice-0.1-py3.7.egg/vpn_slice/main.py", line 245, in parse_env
  File "/usr/local/lib/python3.7/site-packages/vpn_slice-0.1-py3.7.egg/vpn_slice/main.py", line 218, in <lambda>
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 351, in __getitem__
    return cls._member_map_[name]
KeyError: 'attempt_reconnect'`

**Comment by gmacon** [comment]
@modib, I believe the attempt-reconnect error is a separate issue, so I create #13 to discuss it.

**Comment by doomedraven** [comment]
confirmed, works on osx 10.14.3 with openconnect  8.02.
@gmacon  thanks a lot

**Comment by michaelblyons** [comment]
What are the odds that this could be a Homebrew formula?

**Comment by doomedraven** [comment]
You can install it with pip if that would be merged

**Comment by XL64** [comment]
Toi can even install the branch directly if toi don't want tout wait for
the merge.

Le mer. 6 mars 2019 à 18:01, doomedraven <notifications@github.com> a
écrit :

**Comment by doomedraven** [comment]
Yes is what i have done, but merge would be better for all of us :)

**Comment by doomedraven** [comment]
if that would be useful for someone, vpn-slice + unbound dns server in local
https://github.com/doomedraven/Tools/blob/master/Mac/VPN_split.sh

**Comment by XL64** [comment]
In your script didn’t you mean
sudo cat >> /usr/local/etc/unbound/unbound.conf << EOF$
Instead of
cat >> /usr/local/etc/unbound/unbound.conf <<< EOL

I suppose after that you don’t need to give a list of adresses to resolve to vpn-slice juste a range of IP to pass via the tunnel ?

**Comment by doomedraven** [comment]
you are correct, fixing, yes the dns will handle that dynamically for you, and you don't need use hosts or pass list of domains

**Comment by XL64** [comment]
Hello again,

I must have missed something.
I did copy your configuration at the end of ubound.conf and changed yourcompany.com by  something like my company.corp.local and started ubound and set the DNS to 127.0.0.1.	
I then started openconnect with vpn-slice and a list of subnets to route.
DNS resolution of internet domains works but not for « something.mycompany.corp.local » .
Did I miss something ?
Do you have documentation I should read ?

Regards,

XL.

**Comment by doomedraven** [comment]
you don't need to put .local at the end, just yourcompany.com. <- dot at the end :) 

i just updated it as i forgot what i had updated it here so 1 more thing
`local-data: "vpn.yourcomapy.com.  IN A VPN_IP"` <- required to be able to connect to vpn gw as if no, dns will not able to connect to that dns , see `"company.net."`, you will need real IP in local-data

```
    private-domain: "company.net."
    local-data: "vpn.company.net.     IN A IP"
remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    server-key-file: "/usr/local/etc/unbound/unbound_server.key"
    server-cert-file: "/usr/local/etc/unbound/unbound_server.pem"
    control-key-file: "/usr/local/etc/unbound/unbound_control.key"
    control-cert-file: "/usr/local/etc/unbound/unbound_control.pem"

forward-zone:
   name: "company.net."
   forward-addr: IP
   forward-addr: IP 

forward-zone:
   name: "."
   # forward-ssl-upstream: yes
   forward-addr: 1.1.1.1@53#one.one.one.one
   forward-addr: 8.8.8.8@53#dns.google
   forward-addr: 9.9.9.9@53#dns.quad9.net
   forward-addr: 1.0.0.1@53#one.one.one.one
   forward-addr: 8.8.4.4@53#dns.google
   forward-addr: 149.112.112.112@53#dns.quad9.net
```

**Comment by doomedraven** [comment]
ayway let me know if you need help, so i can maybe better explain it

**Comment by XL64** [comment]
Hello again,

I think I understood what’s still wrong with my config, I need to replace dns1/dns2 by the IP of my internal DNS in the VPN network, right ?
I then have to figure out what it is :)

Thanks,

XL.

**Comment by doomedraven** [comment]
yes correct, that is the easier one, you was need just to check vpn-slice --help, just add to `vpn-slice --dump --verbose`

and it will give you all info

**Comment by XL64** [comment]
Thanks, I retrieved the IP but the DNS resolution is still broken.
I think I took too much of your time and will keep with the openconnect/ocproxy/foxyproxy solution I have in place.

Regards,

XL.

**Comment by doomedraven** [comment]
to check your dns do few things


`dig @dns_IP some_corp_domain`
`dig @localhost some_corp_domain`

to simplify debug of issue in unbound.conf uncomment
```
# logfile: "/tmp/unbound.log"
# log-queries: yes
# log-time-ascii: yes
```

and do `tail -f /tmp/unbound.log` in another terminal, and exec dig command to see whats going on

**Comment by XL64** [comment]
Thanks lot, I’ll try that !

**Comment by XL64** [comment]
Hello Doomedrave,

I fixed some issues :
  - some files where missing : I was listing the sudo in front of unbound-anchor -a /usr/local/etc/unbound/root.key and unbound-control-setup -d /usr/local/etc/unbound
  - The service couldn’t start correctly with brew services start unbound (user agent) because I also started it as daemon (with sudo).

Now my dig is correct but resolution within firefox/safari is not good.

Regards,

XL

**Comment by doomedraven** [comment]
thanks for feedback i will add some checks in there.

about resolitions you mean they are slow or not resolving? need details :P

**Comment by XL64** [comment]
It is not resolving within the browser, but I just notice I had some zombie open connect running… Maybe it is linked...

**Comment by doomedraven** [comment]
if browser not resolve, you can try `dig @company_dns domain` and if that works, than its browser problem, and would need to investigate WTF, but should works, im using that for 3 days already without any problem

**Comment by XL64** [comment]
Ok thanks a lot for all your help !

**Comment by doomedraven** [comment]
i hope @dlenski will merge this PR one day :)

**Comment by XL64** [comment]
Ok @doomedraven, I didn’t add the required IP/subnet to my vpn-slice, the DNS was OK but the route to reach the IP was not.
Now I just cannot run a kinit within a VPN-SLICE but I never managed to do it without full VPN access…
All other seems working.

**Comment by doomedraven** [comment]
how do you execute the openconnect? can you post full command line?

**Comment by XL64** [comment]
I just do

```
echo -e $(security find-generic-password -wa 'MY_LOGIN' -l 'MY_KEYCHAIN_ENTRY_NAME')| \
    sudo openconnect <TheVpnUrl>                                                      \
         -g <TheVpnGroup>                                                             \
         --pid-file=/tmp/vpn_pid_file_does_not_work_but_I_dont_care                   \
         --servercert <mycert>                                                        \
         -u <myLogin> -s                                                              \
         "vpn-slice -v --dump 10.0.0.0/9" #that subnet is maybe too large ... :)
```

**Comment by doomedraven** [comment]
hm, i just do this `sudo openconnect vpn.company.com -u my_user -s 'vpn-slice 10.0.0.0/8 --verbose --dump'`

and it works fine, try maybe cidr 8 instead of 9

**Comment by XL64** [comment]
Finally my kinit issue was not link with that at all, I just had to copy my company krb5.conf in /etc/, all is fine now !

**Comment by doomedraven** [comment]
glad that works :)

**Comment by sjuxax** [comment]
Works great for me at https://github.com/gmacon/vpn-slice/commit/eb4f7e3e2a871bc797fcc771fd250a90bfba85d6. Thanks!

**Comment by emulated24** [comment]
Hi gmacon, great job, thanks a lot for the mac port. ;)
Works fine on macOS Mojave 10.14.4 with OpenConnect for Juniper VPN.

**Comment by dlenski** [comment]
Sorry for the long delay… and many thanks to @gmacon for the excellent, excellent work of abstracting and porting to macOS. :+1: :+1: :+1:

I fixed several bits of `ip route` handling that were broken in 5ff39ee, a couple things that were made more sloppy than necessary in fd571e7 and b6bea08, and a couple cosmetic nickpicks in ca0e574 and d932ba0. Then I also factored out a couple more OS-specific bits into `ProcessProvider` in f47a35c. 

macOS users, please test and let me know if this is still working for you guys. (It should be… I really didn't change anything of consequence in `mac.py`.)

With this we should be in a very good position to port to other BSDs, if anyone's interested.

**Comment by dlenski** [comment]
Turns out the `DigProvider` was also oversimplified, mishandling the case of multiple search domains. Fixed in 3266a8a.

Being able to do `vpn-slice -d corp.com -d alternate.corp.com shorthostname1 shorthostname2 shorthostname3` and have all the hostnames found correctly is a very important use case for me.

**Comment by dlenski** [comment]
One last thing for @gmacon: is there a known minimum version of macOS required for this to work?

**Comment by doomedraven** [comment]
hey @dlenski  thanks for start lookin on this, so now with all your changes

```
Traceback (most recent call last):
  File "/usr/local/bin/vpn-slice", line 11, in <module>
    load_entry_point('vpn-slice', 'console_scripts', 'vpn-slice')()
  File "/private/tmp/vpn-slice/vpn_slice/main.py", line 341, in main
    providers = get_default_providers()
  File "/private/tmp/vpn-slice/vpn_slice/main.py", line 29, in get_default_providers
    from .generic import NoFirewallProvider, NoTunnelPrepProvider
ImportError: cannot import name 'NoTunnelPrepProvider' from 'vpn_slice.generic' (/private/tmp/vpn-slice/vpn_slice/generic.py)
```

**Comment by dlenski** [comment]
@doomedraven, derp derp derp :man_facepalming:. Fixed in edfa341. Thanks for testing.

**Comment by doomedraven** [comment]
now works just fine :) thanks a lot

**Comment by dlenski** [comment]
I'm gonna merge and assume we can clean up any other leftover bits later as needed. Thanks again to @gmacon for the great work and others, in particular @doomedraven, for testing and refinement.

**Comment by doomedraven** [comment]
amazing, thanks a lot @dlenski and @gmacon . I have updated my script https://github.com/doomedraven/Tools/blob/master/Mac/VPN_split.sh

**Comment by gmacon** [comment]
> One last thing for @gmacon: is there a known minimum version of macOS required for this to work?

I don't know what the minimum required version is, but I suspect that it would work on any version of macOS because the tools we're interacting with here were all inherited from FreeBSD.

**Comment by dlenski** [comment]
> I don't know what the minimum required version is, but I suspect that it would work on any version of macOS because the tools we're interacting with here were all inherited from FreeBSD.

Thanks. I googled around some, and that was my impression… the userland interface for routing on macOS doesn't seem to have changed much in the last ~20 years. So I'll just leave the docs as-is unless we find a clear counterexample.

**Comment by kalvinwang** [comment]
Thank you @dlenski @gmacon @doomedraven et al!!!

**Comment by drewclauson** [comment]
Thanks all, I've got this pulled down and working! 👏🏻👏🏻

**Comment by dlenski** [comment]
I'm going to lock this issue, so that if any *new issues* with Mac support are found… people will open *new issues* rather than be tempted to pile on this one. :sunglasses:

**Pull request merged**
